data <- read.table(pipe('findstr /B /R ^[1-2]/2/2007 household_power_consumption.txt'),header=F, sep=';')
colnames(data) <-names(read.table('household_power_consumption.txt', header=TRUE,sep=";",nrows=1))
x <- paste(data$Date, data$Time)
dt<-strptime(x, "%d/%m/%Y %H:%M:%S")
windows()
par(bg = 'white')
plot(dt,data$Sub_metering_1,type='n', xlab="", ylab="Energy sub metering")
points(dt,data$Sub_metering_1,type='l',col="black")
points(dt,data$Sub_metering_2,type='l',col="red")
points(dt,data$Sub_metering_3,type='l',col="blue")
legend("topright", pch='',lwd=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png, file = "plot3.png")
dev.off()