data <- read.table(pipe('findstr /B /R ^[1-2]/2/2007 household_power_consumption.txt'),header=F, sep=';')
colnames(data) <-names(read.table('household_power_consumption.txt', header=TRUE,sep=";",nrows=1))
x <- paste(data$Date, data$Time)
dt<-strptime(x, "%d/%m/%Y %H:%M:%S")
windows()
plot(dt,data$Global_active_power,type='l', xlab="", ylab="Global Active Power (kilowatts)")
dev.copy(png, file = "plot2.png")
dev.off()